import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StyledComponentsRegistry from "@lib/registry";
import StyleProvider from "@theme/StyleProvider";
import Header from "@components/header/Header";
import ReduxProvider from "@redux/provider";
import { Block, Footer, SideDrawer } from "@components/index";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StyledComponentsRegistry>
          <StyleProvider>
            <ReduxProvider>
              <Header/>
              <SideDrawer />
              <Block
                customStyles={{
                  flex: '1',
                  marginTop: '145px',
                  display: `block`,
                }}
              >
                {children}
              </Block>
              <Footer />
            </ReduxProvider>
          </StyleProvider>  
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
